
spring:
  application:
    name: eureka-server

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol: smtp
    test-connection: false
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.connectiontimeout: 30000

  # default port for eureka server
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      default-zone: http://localhost:8888/eureka
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

image-service:
  url: localhost:8088