spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: davidkambomoi@gmail.com
    password: kiennguyen
    protocol: smtp
    test-connection: false
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.connectiontimeout: 30000