version: '3.8'
#containers => services
services:
  mysql-springboot-container-three:
    image: mysql:8.0.30
    container_name:   mysql-springboot-container-three
    ports:
      - 3310:3306
    volumes:
      - mysql-springboot-data:/var/lib/mysql
      - mysql-springboot-config-deamond:/etc/mysql/conf.d
    networks:
      - backend
    environment:
      MYSQL_USER: kien
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testconfigs
  springboot-docker-container:
    image: miracle98/springboot-docker:v1.0.0
    container_name: springboot-container
    ports:
      - 8085:8089
    volumes:
      - ./:/app
    networks:
      - backend
#create network
networks:
  backend:
    name: springboot-app-network
volumes:
  mysql-springboot-data:
  mysql-springboot-config-deamond:

